# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_0.0.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(280, 191)
        self.L1 = QtWidgets.QLabel(Login)
        self.L1.setGeometry(QtCore.QRect(0, 0, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(18)
        self.L1.setFont(font)
        self.L1.setAlignment(QtCore.Qt.AlignCenter)
        self.L1.setObjectName("L1")
        self.L2 = QtWidgets.QLabel(Login)
        self.L2.setGeometry(QtCore.QRect(0, 30, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Swis721 LtCn BT")
        font.setPointSize(18)
        self.L2.setFont(font)
        self.L2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.L2.setMidLineWidth(0)
        self.L2.setAlignment(QtCore.Qt.AlignCenter)
        self.L2.setObjectName("L2")
        self.T3 = QtWidgets.QLineEdit(Login)
        self.T3.setGeometry(QtCore.QRect(120, 80, 150, 20))
        self.T3.setObjectName("T3")
        self.L3 = QtWidgets.QLabel(Login)
        self.L3.setGeometry(QtCore.QRect(10, 80, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.L3.setFont(font)
        self.L3.setObjectName("L3")
        self.L4 = QtWidgets.QLabel(Login)
        self.L4.setGeometry(QtCore.QRect(10, 110, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.L4.setFont(font)
        self.L4.setObjectName("L4")
        self.T4 = QtWidgets.QLineEdit(Login)
        self.T4.setGeometry(QtCore.QRect(120, 110, 150, 20))
        self.T4.setObjectName("T4")
        self.B1 = QtWidgets.QPushButton(Login)
        self.B1.setGeometry(QtCore.QRect(10, 150, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Swis721 LtCn BT")
        font.setPointSize(12)
        self.B1.setFont(font)
        self.B1.setObjectName("B1")
        self.B2 = QtWidgets.QPushButton(Login)
        self.B2.setGeometry(QtCore.QRect(170, 150, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Swis721 LtCn BT")
        font.setPointSize(12)
        self.B2.setFont(font)
        self.B2.setObjectName("B2")

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.L1.setText(_translate("Login", "Dan1"))
        self.L2.setText(_translate("Login", "<html><head/><body><p><span style=\" color:#aaaaaa;\">Login</span></p></body></html>"))
        self.L3.setText(_translate("Login", "<html><head/><body><p><span style=\" color:#aaaaaa;\">Usuario</span></p></body></html>"))
        self.L4.setText(_translate("Login", "<html><head/><body><p><span style=\" color:#aaaaaa;\">Contraseña</span></p></body></html>"))
        self.B1.setText(_translate("Login", "Entrar"))
        self.B2.setText(_translate("Login", "Cancelar"))
